//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Gateway.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Gateway.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string InValidOtpCode {
            get {
                return ResourceManager.GetString("InValidOtpCode", resourceCulture);
            }
        }
        
        internal static string Error_400 {
            get {
                return ResourceManager.GetString("Error_400", resourceCulture);
            }
        }
        
        internal static string Error_401 {
            get {
                return ResourceManager.GetString("Error_401", resourceCulture);
            }
        }
        
        internal static string Error_404 {
            get {
                return ResourceManager.GetString("Error_404", resourceCulture);
            }
        }
        
        internal static string Error_403 {
            get {
                return ResourceManager.GetString("Error_403", resourceCulture);
            }
        }
        
        internal static string Error_500 {
            get {
                return ResourceManager.GetString("Error_500", resourceCulture);
            }
        }
        
        internal static string Error_Unknown {
            get {
                return ResourceManager.GetString("Error_Unknown", resourceCulture);
            }
        }
        
        internal static string NoRemainingMessageCount {
            get {
                return ResourceManager.GetString("NoRemainingMessageCount", resourceCulture);
            }
        }
        
        internal static string NoRemainingBoostCount {
            get {
                return ResourceManager.GetString("NoRemainingBoostCount", resourceCulture);
            }
        }
        
        internal static string NoRemainingKissCount {
            get {
                return ResourceManager.GetString("NoRemainingKissCount", resourceCulture);
            }
        }
        
        internal static string NotPremium {
            get {
                return ResourceManager.GetString("NotPremium", resourceCulture);
            }
        }
    }
}
